var details = [
  {'name': 'Aditya Gautam', 'domain': 'App Development'},
  {'name': 'Hitesh Tripathi', 'domain': 'Web Development'},
  {'name': 'Rishabh Singh', 'domain': 'App Development'},
  {'name': 'Apoorv Jain', 'domain': 'Machine Learning'},
  {'name': 'Tarun Raghav', 'domain': 'Machine Learning'},
  {'name': 'Pranjal Maurya', 'domain': 'Management'},
  {'name': 'Anshika Bajpai', 'domain': 'App Development'},
  {'name': 'Vishesh Dhawan', 'domain': 'Web Development'},
  {'name': 'Pranjul Itondia', 'domain': 'Machine Learning'},
  {'name': 'Shatakshi Upadhyay', 'domain': 'App Development'},
  {'name': 'Krishna Agarwal', 'domain': 'Web Development'},
  {'name': 'Shubh Shah', 'domain': 'Management'},
  {'name': 'Ayushi Bansal', 'domain': 'Management'},
  {'name': 'Nirbhay Shukla', 'domain': 'App Development'},
  {'name': 'Himani Chauhan', 'domain': 'Web Development'},
  {'name': 'Nihal', 'domain': 'Machine Learning'},
  {'name': 'Vishesh Kushwaha', 'domain': 'Machine Learning'},
  {'name': 'Shivam Bisht', 'domain': 'Web Development'},
];
